force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Used for logging exceptions</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ApexMethodName__c.field-meta.xml
<CustomField>
    <fullName>ApexMethodName__c</fullName>
    <label>Apex Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <label>HTTP Method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/HttpStatusCode__c.field-meta.xml
<CustomField>
    <fullName>HttpStatusCode__c</fullName>
    <label>HTTP Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/utils/frameworks/logging/classes/LogService.cls
public without sharing class LogService {

    private static final String LOG_TYPE_INTEGRATION_API = 'Integration API';
    private static final String LOG_TYPE_INTEGRATION_CALLOUT= 'Integration Callout';
    private static final String LOG_TYPE_EXCEPTION= 'Exception';

    public static void logIntegrationCallout(HttpRequest request, HttpResponse response) {
        LogEvent__e log = new LogEvent__e();
        log.Type__c = LOG_TYPE_INTEGRATION_CALLOUT;
        log.Endpoint__c = request?.getEndpoint();
        log.HttpMethod__c = request?.getMethod();
        log.HttpStatusCode__c = response?.getStatusCode();
        log.RequestBody__c = StringUtils.truncate(request?.getBody(), 10000);
        log.ResponseBody__c = StringUtils.truncate(response?.getBody(), 10000);

        EventBus.publish(log);
    }

    public static void logIntegrationAPI() {
        if (RestContext.request == null) { return; }

        LogEvent__e log = new LogEvent__e();
        log.Type__c = LOG_TYPE_INTEGRATION_API;
        log.Endpoint__c = RestContext.request?.requestURI;
        log.HttpMethod__c = RestContext.request?.httpMethod;
        log.HttpStatusCode__c = RestContext.response?.statusCode;
        log.RequestBody__c = StringUtils.truncate(RestContext.request?.requestBody?.toString(), 10000);
        log.ResponseBody__c = StringUtils.truncate(RestContext.response?.responseBody?.toString(), 10000);

        EventBus.publish(log);
    }

    public static void logException(Exception e) {
        if (e == null) { return; }

        final String stackTrace = e.getStackTraceString().substringBefore('\n');
        final String className = stackTrace.substringAfter('.').substringBefore('.');
        final String methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');

        LogEvent__e log = new LogEvent__e();
        log.Type__c = LOG_TYPE_EXCEPTION;
        log.ApexClassName__c = className;
        log.ApexMethodName__c = methodName;
        log.StackTrace__c = e.getStackTraceString();
        log.ExceptionType__c = e.getTypeName();
        log.ExceptionMessage__c = e.getMessage();

        EventBus.publish(log);
    }
}