force-app/main/default/objects/IntegrationSetting__mdt/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AIServiceFactory.cls
public with sharing class AIServiceFactory {

    @TestVisible
    private static String mockProvider;

    public static IAIService getService() {
        String provider = mockProvider ?? IntegrationSetting__mdt.getInstance('AIProvider')?.Id__c;

        switch on provider {
            when 'Openai' { return OpenAiServiceFactory.getService(); }
            when 'Gemini' { return GeminiServiceFactory.getService(); }
            when else {
                throw new AIServiceFactoryNotValidProviderException('The AI provider is not valid. Please check the Integration Setting.');
            }
        }
    }

    public class AIServiceFactoryNotValidProviderException extends Exception {}
}