force-app/utils/frameworks/logging/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/utils/frameworks/logging/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Integration API</fullName>
            </value>
            <value>
                <fullName>Integration Callout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/utils/frameworks/logging/tests/LogQueueableTest.cls
@isTest
private class LogQueueableTest {

    @isTest
    static void shouldEnqueueLogQueueableJob() {
        Log__c log = new Log__c();
        log.Type__c = 'Exception';

        Test.startTest();
            Id jobID = System.enqueueJob(new LogQueueable(new List<Log__c>{ log }));
        Test.stopTest();

        Log__c createdLog = [SELECT Type__c FROM Log__c LIMIT 1];

        Assert.isNotNull(jobID, 'Job ID should not be null after enqueueing the job.');
        Assert.areEqual(log.Type__c, createdLog.Type__c, 'Log type should be Exception');
    }
}