force-app/utils/frameworks/logging/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/utils/frameworks/logging/objects/Log__c/fields/ExceptionCodeLine__c.field-meta.xml
<CustomField>
    <fullName>ExceptionCodeLine__c</fullName>
    <label>Exception Code Line</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/utils/frameworks/logging/objects/Log__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/utils/frameworks/logging/objects/Log__c/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <label>Http Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/utils/frameworks/logging/objects/Log__c/fields/HttpStatusCode__c.field-meta.xml
<CustomField>
    <fullName>HttpStatusCode__c</fullName>
    <label>Http Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>103</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>201</fullName>
            </value>
            <value>
                <fullName>202</fullName>
            </value>
            <value>
                <fullName>203</fullName>
            </value>
            <value>
                <fullName>204</fullName>
            </value>
            <value>
                <fullName>205</fullName>
            </value>
            <value>
                <fullName>206</fullName>
            </value>
            <value>
                <fullName>207</fullName>
            </value>
            <value>
                <fullName>208</fullName>
            </value>
            <value>
                <fullName>226</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>301</fullName>
            </value>
            <value>
                <fullName>302</fullName>
            </value>
            <value>
                <fullName>303</fullName>
            </value>
            <value>
                <fullName>304</fullName>
            </value>
            <value>
                <fullName>305</fullName>
            </value>
            <value>
                <fullName>307</fullName>
            </value>
            <value>
                <fullName>308</fullName>
            </value>
            <value>
                <fullName>400</fullName>
            </value>
            <value>
                <fullName>401</fullName>
            </value>
            <value>
                <fullName>402</fullName>
            </value>
            <value>
                <fullName>403</fullName>
            </value>
            <value>
                <fullName>404</fullName>
            </value>
            <value>
                <fullName>405</fullName>
            </value>
            <value>
                <fullName>406</fullName>
            </value>
            <value>
                <fullName>407</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/utils/frameworks/logging/objects/Log__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/utils/frameworks/logging/objects/Log__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>Request Body</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/utils/frameworks/logging/objects/Log__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>Response Body</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/utils/frameworks/logging/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/utils/frameworks/logging/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Integration API</fullName>
            </value>
            <value>
                <fullName>Integration Callout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/utils/frameworks/logging/classes/LogHandler.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class LogHandler {

    public static void logIntegrationCallout(HttpRequest request, HttpResponse response) {
        Log__c log = new Log__c();
        log.Type__c = 'Integration Callout';
        log.Endpoint__c = request?.getEndpoint();
        log.HttpMethod__c = request?.getMethod();
        log.RequestBody__c = request?.getBody();
        log.ResponseBody__c = response?.getBody();
        log.HttpStatusCode__c = response?.getStatusCode().toString();

        insert log;
    }

    public static void logIntegrationAPI() {
        if (RestContext.request == null) { return; }

        Log__c log = new Log__c();
        log.Type__c = 'Integration API';
        log.Endpoint__c = RestContext.request?.requestURI;
        log.HttpMethod__c = RestContext.request?.httpMethod;
        log.HttpStatusCode__c = RestContext.response?.statusCode.toString();
        log.RequestBody__c = RestContext.request?.requestBody?.toString();
        log.ResponseBody__c = RestContext.response?.responseBody?.toString();

        insert log;
    }

    public static void logException(Exception e) {
        if (e == null) { return; }

        final String stackTrace = e.getStackTraceString().substringBefore('\n');
        final String className = stackTrace.substringAfter('.').substringBefore('.');
        final String methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');

        Log__c log = new Log__c();
        log.Type__c = 'Exception';
        log.ClassName__c = className;
        log.MethodName__c = methodName;
        log.StackTrace__c = e.getStackTraceString();
        log.ExceptionType__c = e.getTypeName();
        log.ExceptionMessage__c = e.getMessage();
        log.ExceptionCodeLine__c = e.getLineNumber();

        insert log;
    }
}