force-app/main/default/objects/IntegrationEndpoint__mdt/IntegrationEndpoint__mdt.object-meta.xml
<CustomObject>
    <description>Stores integration&apos;s endpoints</description>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationEndpoint__mdt/fields/Accept__c.field-meta.xml
<CustomField>
    <fullName>Accept__c</fullName>
    <label>Accept</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/ld+json</fullName>
            </value>
            <value>
                <fullName>application/octet-stream</fullName>
            </value>
            <value>
                <fullName>application/pdf</fullName>
            </value>
            <value>
                <fullName>application/vnd.api+json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>application/yaml</fullName>
            </value>
            <value>
                <fullName>image/jpeg</fullName>
            </value>
            <value>
                <fullName>image/png</fullName>
            </value>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>text/yaml</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegrationEndpoint__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GitlabService.cls
public with sharing class GitlabService {

    public static HttpResponse requestProjectDetails() {
        IntegrationEndpoint__mdt projectDetailEndpoint = IntegrationEndpoint__mdt.getInstance('GitlabProjectDetails');
        String projectId = IntegrationSetting__mdt.getInstance('GitlabProjectId').Id__c;

        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:GitlabAPI' + projectDetailEndpoint.Endpoint__c.replace('{id}', projectId));
        request.setMethod(projectDetailEndpoint.Method__c);
        request.setHeader('Accept', projectDetailEndpoint.Accept__c);

        return new Http().send(request);
    }
}