force-app/main/default/objects/IntegrationEndpoint__mdt/IntegrationEndpoint__mdt.object-meta.xml
<CustomObject>
    <description>Stores integration&apos;s endpoints</description>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationEndpoint__mdt/fields/Accept__c.field-meta.xml
<CustomField>
    <fullName>Accept__c</fullName>
    <label>Accept</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/ld+json</fullName>
            </value>
            <value>
                <fullName>application/octet-stream</fullName>
            </value>
            <value>
                <fullName>application/pdf</fullName>
            </value>
            <value>
                <fullName>application/vnd.api+json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>application/yaml</fullName>
            </value>
            <value>
                <fullName>image/jpeg</fullName>
            </value>
            <value>
                <fullName>image/png</fullName>
            </value>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>text/yaml</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegrationEndpoint__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>application/graphql</fullName>
                <default>true</default>
                <label>application/graphql</label>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/ld+json</fullName>
            </value>
            <value>
                <fullName>application/octet-stream</fullName>
            </value>
            <value>
                <fullName>application/pdf</fullName>
            </value>
            <value>
                <fullName>application/vnd.api+json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
            <value>
                <fullName>application/yaml</fullName>
            </value>
            <value>
                <fullName>image/jpeg</fullName>
            </value>
            <value>
                <fullName>image/png</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>text/yaml</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegrationEndpoint__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integrations/gitlab/classes/GitlabService.cls
public virtual with sharing class GitlabService {

    private static final String GITLAB_API = 'callout:GitlabAPI';
    private static final String GITLAB_PROJECT_ID = 'GitlabProjectId';
    private static final String GITLAB_MERGE_REQUEST_ID = 'GitlabMergeRequestId';
    private static final String GITLAB_PROJECT_DETAILS = 'GitlabProjectDetails';
    private static final String GITLAB_CREATE_NOTE_ON_MERGE_REQUEST = 'GitlabCreateNoteOnMergeRequest';

    @TestVisible
    private static final String NOTE_EMPTY_MESSAGE = 'Note request body cannot be null or empty.';

    public virtual HttpResponse requestProjectDetails() {
        IntegrationEndpoint__mdt projectDetailEndpoint = IntegrationEndpoint__mdt.getInstance(GITLAB_PROJECT_DETAILS);
        String projectId = IntegrationSetting__mdt.getInstance(GITLAB_PROJECT_ID).Id__c;

        HttpRequest request = new HttpRequest();
        request.setMethod(projectDetailEndpoint.Method__c);
        request.setHeader('Content-Type', projectDetailEndpoint.ContentType__c);
        request.setHeader('Accept', projectDetailEndpoint.Accept__c);
        request.setEndpoint(GITLAB_API + projectDetailEndpoint.Endpoint__c.replace('{id}', projectId));

        return new Http().send(request);
    }

    public virtual HttpResponse postNoteIntoMergeRequest(GitlabMergeRequestNote noteRequest) {
        if (String.isBlank(noteRequest?.body)) {
            throw new GitlabServiceMissingParametersException(NOTE_EMPTY_MESSAGE);
        }

        IntegrationEndpoint__mdt postNoteOnMergeRequestEndpoint = IntegrationEndpoint__mdt.getInstance(GITLAB_CREATE_NOTE_ON_MERGE_REQUEST);
        String projectId = IntegrationSetting__mdt.getInstance(GITLAB_PROJECT_ID).Id__c;
        String mergeRequestId = IntegrationSetting__mdt.getInstance(GITLAB_MERGE_REQUEST_ID).Id__c;

        String endpoint = GITLAB_API + postNoteOnMergeRequestEndpoint.Endpoint__c.replace('{id}', projectId)
                                                                                 .replace('{merge_request_iid}', mergeRequestId);
        endpoint += '?body=' + EncodingUtil.urlEncode(noteRequest.body, 'UTF-8');
        endpoint += '&internal=' + String.valueOf(noteRequest.internal);                           

        HttpRequest request = new HttpRequest();
        request.setMethod(postNoteOnMergeRequestEndpoint.Method__c);
        request.setHeader('Content-Type', postNoteOnMergeRequestEndpoint.ContentType__c);
        request.setHeader('Accept', postNoteOnMergeRequestEndpoint.Accept__c);
        request.setEndpoint(endpoint);

        return new Http().send(request);
    }

    public class GitlabServiceMissingParametersException extends Exception {}
}